production:
  primary:
    adapter: postgresql
    encoding: unicode
    url: <%= ENV['postgresql://hiking_tracker_db_user:NkrOM7W7TsL6DULOwVpg877xEgyCgROK@dpg-d6nfsgn5gffc73bjb3f0-a/hiking_tracker_db'] %>
  cache:
    <<: *default
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate

